<?php

namespace Database\Seeders;

use App\Models\Banco;
use App\Models\Producto;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $bcp_id = Banco::where('nombre', 'BCP')->first()->id;
        $interbank_id = Banco::where('nombre', 'INTERBANK')->first()->id;
        $bbva_id = Banco::where('nombre', 'BBVA')->first()->id;
        $scotiabank_id = Banco::where('nombre', 'SCOTIABANK')->first()->id;
        $productosbcp = [
            // -----------------------
            // PRODUCTOS ACTIVOS
            // -----------------------
            [
                'banco_id' => $bcp_id,
                'categoria' => 'ACTIVO',
                'codigo' => 'P1_BCP',
                'tipo' => 'Préstamo',
                'nombre_comercial' => 'Crédito Personal',
                'moneda' => 'PEN',
                'monto_minimo' => 300.00,
                'monto_maximo' => 350000.00,
                'plazo_minimo_meses' => 3,
                'plazo_maximo_meses' => 72,
                'tea_minimo' => 8.90,
                'tea_maximo' => 87.50,
                'tcea_referencial' => 41.88,
                'seguro_desgravamen_mensual' => 0.00115,
                'seguro_extra' => null,
            ],
            [
                'banco_id' => $bcp_id,
                'categoria' => 'ACTIVO',
                'codigo' => 'P2_BCP',
                'tipo' => 'Préstamo',
                'nombre_comercial' => 'Crédito Vehicular',
                'moneda' => 'PEN',
                'monto_minimo' => 15000.00,
                'monto_maximo' => null,
                'plazo_minimo_meses' => 12,
                'plazo_maximo_meses' => 72,
                'tea_minimo' => 8.00,
                'tea_maximo' => 17.20,
                'tcea_referencial' => 30.30,
                'seguro_desgravamen_mensual' => 0.00077,
                'seguro_extra' => null,
            ],
            [
                'banco_id' => $bcp_id,
                'categoria' => 'ACTIVO',
                'codigo' => 'P3_BCP',
                'tipo' => 'Préstamo',
                'nombre_comercial' => 'Crédito Hipotecario',
                'moneda' => 'PEN',
                'monto_minimo' => 32000.00,
                'monto_maximo' => null,
                'plazo_minimo_meses' => 4,
                'plazo_maximo_meses' => 25,
                'tea_minimo' => null,
                'tea_maximo' => 13.99,
                'tcea_referencial' => 14.82,
                'seguro_desgravamen_mensual' => null,
                'seguro_extra' => 'Individual: 0.030% / Mancomunada: 0.057%',
            ],

            // -----------------------
            // PRODUCTOS PASIVOS
            // -----------------------
            [
                'banco_id' => $bcp_id,
                'categoria' => 'PASIVO',
                'codigo' => 'A1_BCP',
                'tipo' => 'Ahorro',
                'nombre_comercial' => 'Cuenta Digital',
                'moneda' => 'PEN',
                'monto_apertura' => null,
                'tea_minimo' => null,
                'tea_maximo' => null,
                'trea_minima' => null,
                'trea_maxima' => null,
            ],
            [
                'banco_id' => $bcp_id,
                'categoria' => 'PASIVO',
                'codigo' => 'A2_BCP',
                'tipo' => 'Ahorro',
                'nombre_comercial' => 'Cuenta Premio',
                'moneda' => 'PEN',
                'monto_apertura' => 1500.00,
                'tea_minimo' => 0.00,
                'tea_maximo' => 1.00,
                'trea_minima' => 0.25,
                'trea_maxima' => null,
            ],
            [
                'banco_id' => $bcp_id,
                'categoria' => 'PASIVO',
                'codigo' => 'A3_BCP',
                'tipo' => 'Ahorro',
                'nombre_comercial' => 'Cuenta Sueldo',
                'moneda' => 'PEN',
                'monto_apertura' => null,
                'tea_minimo' => null,
                'tea_maximo' => null,
                'trea_minima' => null,
                'trea_maxima' => null,
            ],
            [
                'banco_id' => $bcp_id,
                'categoria' => 'PASIVO',
                'codigo' => 'A4_BCP',
                'tipo' => 'Ahorro',
                'nombre_comercial' => 'Cuenta CTS',
                'moneda' => 'PEN',
                'monto_apertura' => null,
                'tea_minimo' => 1.00,
                'tea_maximo' => 2.50,
                'trea_minima' => null,
                'trea_maxima' => null,
            ],
            [
                'banco_id' => $bcp_id,
                'categoria' => 'PASIVO',
                'codigo' => 'A5_BCP',
                'tipo' => 'Ahorro',
                'nombre_comercial' => 'Cuenta Ilimitada',
                'moneda' => 'PEN',
                'monto_apertura' => null,
                'tea_minimo' => null,
                'tea_maximo' => null,
                'trea_minima' => null,
                'trea_maxima' => 14.40,
            ],
            [
                'banco_id' => $bcp_id,
                'categoria' => 'PASIVO',
                'codigo' => 'I1_BCP',
                'tipo' => 'Inversión',
                'nombre_comercial' => 'Depósito a Plazo Fijo / Banca Digital',
                'moneda' => 'PEN',
                'monto_minimo' => 500.00,
                'monto_maximo' => 1000000.00,
                'plazo_minimo_meses' => 90,
                'plazo_maximo_meses' => 999,
                'tea_minimo' => null,
                'tea_maximo' => null,
                'trea_minima' => null,
                'trea_maxima' => null,
                'seguro_extra' => 'Depende del canal, moneda, monto y plazo de inversión',
            ],
            [
                'banco_id' => $bcp_id,
                'categoria' => 'PASIVO',
                'codigo' => 'I2_BCP',
                'tipo' => 'Inversión',
                'nombre_comercial' => 'Depósito a Plazo Fijo / Por Agencia',
                'moneda' => 'PEN',
                'monto_minimo' => 2000.00,
                'monto_maximo' => null,
                'plazo_minimo_meses' => 90,
                'plazo_maximo_meses' => 999,
                'tea_minimo' => null,
                'tea_maximo' => null,
                'trea_minima' => null,
                'trea_maxima' => null,
                'seguro_extra' => 'Depende del canal, moneda, monto y plazo de inversión',
            ],
        ];
        $productosinterbank = [
            // -----------------------
            // PRODUCTOS ACTIVOS
            // -----------------------
            [
                'banco_id' => $interbank_id,
                'categoria' => 'ACTIVO',
                'codigo' => 'P1_IBK',
                'tipo' => 'Préstamo',
                'nombre_comercial' => 'Crédito Personal/sin aval',
                'moneda' => 'PEN',
                'monto_minimo' => 1000.00,
                'monto_maximo' => 60000.00,
                'plazo_minimo_meses' => 6,
                'plazo_maximo_meses' => 60,
                'tea_minimo' => 8.99,
                'tea_maximo' => 99.90,
                'tcea_referencial' => 51.03,
                'seguro_desgravamen_mensual' => 0.00075, // 0.075%
                'seguro_extra' => null,
            ],
            [
                'banco_id' => $interbank_id,
                'categoria' => 'ACTIVO',
                'codigo' => 'P1A_IBK',
                'tipo' => 'Préstamo',
                'nombre_comercial' => 'Crédito Personal/con aval',
                'moneda' => 'PEN',
                'monto_minimo' => 3000.00,
                'monto_maximo' => null, // No especifica
                'plazo_minimo_meses' => 6,
                'plazo_maximo_meses' => 60,
                'tea_minimo' => 6.99,
                'tea_maximo' => 14.99,
                'tcea_referencial' => null,
                'seguro_desgravamen_mensual' => null,
                'seguro_extra' => null,
            ],
            [
                'banco_id' => $interbank_id,
                'categoria' => 'ACTIVO',
                'codigo' => 'P2_IBK',
                'tipo' => 'Préstamo',
                'nombre_comercial' => 'Crédito Vehicular',
                'moneda' => 'PEN',
                'monto_minimo' => 1500.00,
                'monto_maximo' => null, // No especifica
                'plazo_minimo_meses' => null,
                'plazo_maximo_meses' => null,
                'tea_minimo' => 11.00,
                'tea_maximo' => null,
                'tcea_referencial' => 18.06,
                'seguro_desgravamen_mensual' => 0.000375, // 0.0375% INDIV
                'seguro_extra' => 'Tasa de seguro del vehículo: 3.52% anual; mancomunada 0.00075',
            ],
            [
                'banco_id' => $interbank_id,
                'categoria' => 'ACTIVO',
                'codigo' => 'P3_IBK',
                'tipo' => 'Préstamo',
                'nombre_comercial' => 'Crédito Hipotecario',
                'moneda' => 'PEN',
                'monto_minimo' => null,   // No especifica
                'monto_maximo' => null,   // No especifica
                'plazo_minimo_meses' => 60,
                'plazo_maximo_meses' => 360,
                'tea_minimo' => 8.80,
                'tea_maximo' => null,
                'tcea_referencial' => 9.89,
                'seguro_desgravamen_mensual' => 0.00028,  // 0.028% (indiv)
                'seguro_extra' => 'Mancomunada: 0.052% (0.00052)',
            ],

            // -----------------------
            // PRODUCTOS PASIVOS
            // -----------------------
            [
                'banco_id' => $interbank_id,
                'categoria' => 'PASIVO',
                'codigo' => 'A1_IBK',
                'tipo' => 'Ahorro',
                'nombre_comercial' => 'Cuenta Digital',
                'moneda' => 'PEN',
                'monto_apertura' => null,
                'tea_minimo' => null,
                'tea_maximo' => null,
                'trea_minima' => null,
                'trea_maxima' => null,
            ],
            [
                'banco_id' => $interbank_id,
                'categoria' => 'PASIVO',
                'codigo' => 'A2_IBK',
                'tipo' => 'Ahorro',
                'nombre_comercial' => 'Cuenta Millonaria',
                'moneda' => 'PEN',
                'monto_apertura' => 1500.00,
                'tea_minimo' => null,
                'tea_maximo' => null,
                'trea_minima' => 0.50,
                'trea_maxima' => null,
            ],
            [
                'banco_id' => $interbank_id,
                'categoria' => 'PASIVO',
                'codigo' => 'A3_IBK',
                'tipo' => 'Ahorro',
                'nombre_comercial' => 'Cuenta Súper Tasa',
                'moneda' => 'PEN',
                'monto_apertura' => 10.00,
                'tea_minimo' => null,
                'tea_maximo' => null,
                'trea_minima' => 0.00,
                'trea_maxima' => 4.50,
            ],
            [
                'banco_id' => $interbank_id,
                'categoria' => 'PASIVO',
                'codigo' => 'A4_IBK',
                'tipo' => 'Ahorro',
                'nombre_comercial' => 'Cuenta Sueldo',
                'moneda' => 'PEN',
                'monto_apertura' => null,
                'tea_minimo' => null,
                'tea_maximo' => null,
                'trea_minima' => null,
                'trea_maxima' => null,
            ],
            [
                'banco_id' => $interbank_id,
                'categoria' => 'PASIVO',
                'codigo' => 'A5_IBK',
                'tipo' => 'Ahorro',
                'nombre_comercial' => 'Cuenta Joven',
                'moneda' => 'PEN',
                'monto_apertura' => null,
                'tea_minimo' => null,
                'tea_maximo' => null,
                'trea_minima' => null,
                'trea_maxima' => null,
            ],
            [
                'banco_id' => $interbank_id,
                'categoria' => 'PASIVO',
                'codigo' => 'A6_IBK',
                'tipo' => 'Ahorro',
                'nombre_comercial' => 'Cuenta CTS',
                'moneda' => 'PEN',
                'monto_apertura' => null,
                'tea_minimo' => null,
                'tea_maximo' => null,
                'trea_minima' => 0.25,
                'trea_maxima' => 4.50,
            ],
            [
                'banco_id' => $interbank_id,
                'categoria' => 'PASIVO',
                'codigo' => 'I1_IBK',
                'tipo' => 'Inversión',
                'nombre_comercial' => 'Depósito a Plazo Fijo',
                'moneda' => 'PEN',
                'monto_apertura' => 2000.00,
                'plazo_minimo_meses' => 31,
                'plazo_maximo_meses' => 720,
                'tea_minimo' => null,
                'tea_maximo' => null,
                'trea_minima' => 0.50,
                'trea_maxima' => 4.50,
            ],
        ];
        $productosscotiabank = [
            [
                'banco_id' => $scotiabank_id,
                'categoria' => 'ACTIVO',
                'codigo' => 'P1_Scotiabank',
                'tipo' => 'Préstamo',
                'nombre_comercial' => 'Crédito Personal',
                'moneda' => 'PEN',
                'monto_minimo' => 50000.00,
                'monto_maximo' => null,
                'plazo_minimo_meses' => 6,
                'plazo_maximo_meses' => 60,
                'tea_minimo' => 8.00,
                'tea_maximo' => 70.00,
                'tcea_referencial' => 70.67,
                'seguro_desgravamen_mensual' => 0.001995, // 0.1995%
                'seguro_extra' => 'Individual: 0.1995% | Mancomunada: 0.3990%',
            ],
            [
                'banco_id' => $scotiabank_id,
                'categoria' => 'ACTIVO',
                'codigo' => 'P2_Scotiabank',
                'tipo' => 'Préstamo',
                'nombre_comercial' => 'Crédito Vehicular/con cuenta sueldo',
                'moneda' => 'PEN',
                'monto_minimo' => 24000.00,
                'monto_maximo' => null,
                'plazo_minimo_meses' => 6,
                'plazo_maximo_meses' => 60,
                'tea_minimo' => 8.99,
                'tea_maximo' => 14.99,
                'tcea_referencial' => 25.04,
                'seguro_desgravamen_mensual' => 0.001045, // 0.1045%
                'seguro_extra' => 'Individual: 0.1045% | Mancomunada: 0.2090% | Seguro adicional 0.506%',
            ],
            [
                'banco_id' => $scotiabank_id,
                'categoria' => 'ACTIVO',
                'codigo' => 'P2B_Scotiabank',
                'tipo' => 'Préstamo',
                'nombre_comercial' => 'Crédito Vehicular/sin cuenta sueldo',
                'moneda' => 'PEN',
                'monto_minimo' => 24000.00,
                'monto_maximo' => null,
                'plazo_minimo_meses' => 6,
                'plazo_maximo_meses' => 60,
                'tea_minimo' => 9.99,
                'tea_maximo' => 15.99,
                'tcea_referencial' => null,
                'seguro_desgravamen_mensual' => null,
                'seguro_extra' => null,
            ],
            [
                'banco_id' => $scotiabank_id,
                'categoria' => 'ACTIVO',
                'codigo' => 'P3_Scotiabank',
                'tipo' => 'Préstamo',
                'nombre_comercial' => 'Crédito Hipotecario',
                'moneda' => 'PEN',
                'monto_minimo' => 34000.00,
                'monto_maximo' => null,
                'plazo_minimo_meses' => 9,
                'plazo_maximo_meses' => 360,
                'tea_minimo' => 11.00,
                'tea_maximo' => 14.00,
                'tcea_referencial' => 15.43,
                'seguro_desgravamen_mensual' => 0.000285, // 0.0285%
                'seguro_extra' => 'Individual: 0.0285%-0.0570% | Mancomunada: 0.0546%-0.1092%',
            ],

            // -----------------------
            // PRODUCTOS PASIVOS
            // -----------------------
            [
                'banco_id' => $scotiabank_id,
                'categoria' => 'PASIVO',
                'codigo' => 'A1_Scotiabank',
                'tipo' => 'Ahorro',
                'nombre_comercial' => 'Cuenta Digital',
                'moneda' => 'PEN',
                'monto_apertura' => null,
                'tea_minimo' => null,
                'tea_maximo' => null,
                'trea_minima' => null,
                'trea_maxima' => null,
            ],
            [
                'banco_id' => $scotiabank_id,
                'categoria' => 'PASIVO',
                'codigo' => 'A2_Scotiabank',
                'tipo' => 'Ahorro',
                'nombre_comercial' => 'Cuenta Sueldo',
                'moneda' => 'PEN',
                'monto_apertura' => null,
                'tea_minimo' => null,
                'tea_maximo' => null,
                'trea_minima' => null,
                'trea_maxima' => null,
            ],
            [
                'banco_id' => $scotiabank_id,
                'categoria' => 'PASIVO',
                'codigo' => 'A3_Scotiabank',
                'tipo' => 'Ahorro',
                'nombre_comercial' => 'Cuenta Power',
                'moneda' => 'PEN',
                'monto_apertura' => 1500.00,
                'tea_minimo' => null,
                'tea_maximo' => null,
                'trea_minima' => 0.25,
                'trea_maxima' => 4.60,
            ],
            [
                'banco_id' => $scotiabank_id,
                'categoria' => 'PASIVO',
                'codigo' => 'A4_Scotiabank',
                'tipo' => 'Ahorro',
                'nombre_comercial' => 'Cuenta Meta',
                'moneda' => 'PEN',
                'monto_apertura' => null,
                'tea_minimo' => null,
                'tea_maximo' => null,
                'trea_minima' => null,
                'trea_maxima' => 4.30,
            ],
            [
                'banco_id' => $scotiabank_id,
                'categoria' => 'PASIVO',
                'codigo' => 'A5_Scotiabank',
                'tipo' => 'Ahorro',
                'nombre_comercial' => 'Cuenta CTS',
                'moneda' => 'PEN',
                'monto_apertura' => null,
                'tea_minimo' => null,
                'tea_maximo' => null,
                'trea_minima' => null,
                'trea_maxima' => 4.30,
            ],
            [
                'banco_id' => $scotiabank_id,
                'categoria' => 'PASIVO',
                'codigo' => 'I1_Scotiabank',
                'tipo' => 'Inversión',
                'nombre_comercial' => 'Depósito a Plazo Fijo / Por Agencia',
                'moneda' => 'PEN',
                'monto_apertura' => 1000.00,
                'plazo_minimo_meses' => 1, // 30 días aprox
                'plazo_maximo_meses' => 36, // 1080 días aprox
                'tea_minimo' => null,
                'tea_maximo' => null,
                'trea_minima' => null,
                'trea_maxima' => null,
            ],
        ];
        $productosbbva = [
            // ======================
            // PRODUCTOS ACTIVOS
            // ======================
            [
                'banco_id' => $bbva_id,
                'categoria' => 'ACTIVO',
                'codigo' => 'P1_BBVA',
                'tipo' => 'Préstamo',
                'nombre_comercial' => 'Crédito Personal',
                'moneda' => 'PEN',
                'monto_minimo' => 700.00,
                'monto_maximo' => 100000.00,
                'plazo_minimo_meses' => 6,
                'plazo_maximo_meses' => 72,
                'tea_minimo' => 10.50,
                'tea_maximo' => 115.14,
                'tcea_referencial' => 91.50,
                'seguro_desgravamen_mensual' => 0.00069, // 0.069%
                'seguro_extra' => 'Individual: 0.069% | Mancomunado: 0.129% (mensual)',
            ],
            [
                'banco_id' => $bbva_id,
                'categoria' => 'ACTIVO',
                'codigo' => 'P2_BBVA',
                'tipo' => 'Préstamo',
                'nombre_comercial' => 'Crédito Vehicular',
                'moneda' => 'PEN',
                'monto_minimo' => 11000.00,
                'monto_maximo' => null, // 90% (financiamiento) - no monto exacto
                'plazo_minimo_meses' => 6,
                'plazo_maximo_meses' => 72,
                'tea_minimo' => 9.90,
                'tea_maximo' => 16.99,
                'tcea_referencial' => 40.56,
                'seguro_desgravamen_mensual' => 0.00069, // 0.069%
                'seguro_extra' => 'Mancomunado: 0.129% (mensual)',
            ],
            [
                'banco_id' => $bbva_id,
                'categoria' => 'ACTIVO',
                'codigo' => 'P3_BBVA',
                'tipo' => 'Préstamo',
                'nombre_comercial' => 'Crédito Hipotecario',
                'moneda' => 'PEN',
                'monto_minimo' => 15000.00,
                'monto_maximo' => null, // 90% (financiamiento)
                'plazo_minimo_meses' => 6,
                'plazo_maximo_meses' => 360,
                'tea_minimo' => 16.30,
                'tea_maximo' => 17.50,
                'tcea_referencial' => 13.68,
                'seguro_desgravamen_mensual' => 0.00028, // 0.028%
                'seguro_extra' => 'Mancomunado: 0.052% (mensual)',
            ],

            // ======================
            // PRODUCTOS PASIVOS
            // ======================
            [
                'banco_id' => $bbva_id,
                'categoria' => 'PASIVO',
                'codigo' => 'A1_BBVA',
                'tipo' => 'Ahorro',
                'nombre_comercial' => 'Cuenta Digital',
                'moneda' => 'PEN',
                'monto_apertura' => null,
                'tea_minimo' => null,
                'tea_maximo' => null,
                'trea_minima' => null,
                'trea_maxima' => null,
            ],
            [
                'banco_id' => $bbva_id,
                'categoria' => 'PASIVO',
                'codigo' => 'A2_BBVA',
                'tipo' => 'Ahorro',
                'nombre_comercial' => 'Cuenta Independiente',
                'moneda' => 'PEN',
                'monto_apertura' => null,
                'tea_minimo' => null,
                'tea_maximo' => null,
                'trea_minima' => null,
                'trea_maxima' => null,
            ],
            [
                'banco_id' => $bbva_id,
                'categoria' => 'PASIVO',
                'codigo' => 'A3_BBVA',
                'tipo' => 'Ahorro',
                'nombre_comercial' => 'Cuenta Ganador',
                'moneda' => 'PEN',
                'monto_apertura' => 1500.00,
                'tea_minimo' => 0.00,
                'tea_maximo' => 0.50,
                'trea_minima' => 0.25,
                'trea_maxima' => 0.50,
            ],
            [
                'banco_id' => $bbva_id,
                'categoria' => 'PASIVO',
                'codigo' => 'A4_BBVA',
                'tipo' => 'Ahorro',
                'nombre_comercial' => 'Cuenta Sueldo',
                'moneda' => 'PEN',
                'monto_apertura' => null,
                'tea_minimo' => null,
                'tea_maximo' => null,
                'trea_minima' => null,
                'trea_maxima' => null,
            ],
            [
                'banco_id' => $bbva_id,
                'categoria' => 'PASIVO',
                'codigo' => 'A5_BBVA',
                'tipo' => 'Ahorro',
                'nombre_comercial' => 'Cuenta Vip Wellness',
                'moneda' => 'PEN',
                'monto_apertura' => 10000.00,
                'tea_minimo' => null,
                'tea_maximo' => null,
                'trea_minima' => 0.25,
                'trea_maxima' => 4.50,
            ],
            [
                'banco_id' => $bbva_id,
                'categoria' => 'PASIVO',
                'codigo' => 'A6_BBVA',
                'tipo' => 'Ahorro',
                'nombre_comercial' => 'Cuenta CTS',
                'moneda' => 'PEN',
                'monto_apertura' => null,
                'tea_minimo' => null,
                'tea_maximo' => null,
                'trea_minima' => 1.10,
                'trea_maxima' => 2.60,
            ],
            [
                'banco_id' => $bbva_id,
                'categoria' => 'PASIVO',
                'codigo' => 'I1_BBVA',
                'tipo' => 'Inversión',
                'nombre_comercial' => 'Depósito a Plazo Fijo',
                'moneda' => 'PEN',
                'monto_apertura' => 500.00,
                'plazo_minimo_meses' => 6,
                'plazo_maximo_meses' => 36,
                'trea_minima' => 4.00,
                'trea_maxima' => 4.25,
            ],
        ];
        foreach ($productosbbva as $p) {
            Producto::create($p);
        }
        foreach ($productosscotiabank as $producto) {
            Producto::create($producto);
        }
        foreach ($productosbcp as $p) {
            Producto::create($p);
        }
        foreach ($productosinterbank as $producto) {
            Producto::create($producto);
        }

    }
}
